version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: "dockerhub-auth:username"
    DOCKER_PASSWORD: "dockerhub-auth:password"

phases:
  pre_build:
    commands:
      - echo Logging into DockerHub...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"%s.dkr.ecr.%s.amazonaws.com/%s:%s","Update":"true"},"Ports":[{"ContainerPort":8000}]}' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $IMAGE_REPO_NAME $IMAGE_TAG > Dockerrun.aws.json
      - echo "CHECK ARTIFACTS"
      - ls -R artifacts || echo "NO ARTIFACTS"

artifacts:
  files:
    - Dockerrun.aws.json