AdaBoost:
  accuracy: 0.5985377201728149
  best_params:
    learning_rate: 0.1
    n_estimators: 50
Gradient Boost:
  accuracy: 0.6156530408773679
  best_params:
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 100
Logistic Regression:
  accuracy: 0.6274509803921569
  best_params:
    C: 0.1
    max_iter: 250
    solver: lbfgs
Random Forest:
  accuracy: 0.5874044533067464
  best_params:
    max_depth: 20
    min_samples_split: 5
    n_estimators: 100
XGBoost:
  accuracy: 0.6216350947158524
  best_params:
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 100
